const PRODUCTS=[
{id:1,type:'EA',name:'Gold Scalper Pro EA',price:49,rating:4.8,tag:'MT5',desc:'XAUUSD scalping Expert Advisor with configurable risk controls.',file:'gold-scalper-pro.ex5'},
{id:2,type:'EA',name:'Forex Trend Rider EA',price:39,rating:4.7,tag:'MT4/MT5',desc:'Trend-following automation with session and risk filters.',file:'trend-rider.ex5'},
{id:3,type:'DBOT',name:'Over 2 / Under 8 DBot',price:19,rating:4.6,tag:'DERIV',desc:'Importable Deriv Bot XML template for demo testing and customization.',file:'over-under.xml'},
{id:4,type:'DBOT',name:'Digit Momentum DBot',price:29,rating:4.5,tag:'DERIV',desc:'Configurable Deriv digit automation template with staking controls.',file:'digit-momentum.xml'},
{id:5,type:'INDICATOR',name:'Liquidity Sweep Indicator',price:25,rating:4.9,tag:'TRADINGVIEW',desc:'Liquidity sweep and market-structure indicator concept with alerts.',file:'liquidity-sweep.pine'},
{id:6,type:'INDICATOR',name:'Smart Gold Signals',price:22,rating:4.7,tag:'MT5',desc:'Gold market signal and level indicator for discretionary traders.',file:'smart-gold.ex5'},
{id:7,type:'STRATEGY',name:'XAUUSD Scalping System',price:15,rating:4.8,tag:'PDF+PRESETS',desc:'Rule-based gold scalping playbook with entry, risk and session presets.',file:'xauusd-strategy.pdf'},
{id:8,type:'STRATEGY',name:'Forex Liquidity Strategy',price:18,rating:4.6,tag:'PDF',desc:'Market-structure and liquidity trading framework with examples.',file:'liquidity-strategy.pdf'}];
let cart=JSON.parse(localStorage.getItem('sdt_cart')||'[]');
let orders=JSON.parse(localStorage.getItem('sdt_orders')||'[]');
function money(n){return '$'+Number(n).toFixed(2)}
function save(){localStorage.setItem('sdt_cart',JSON.stringify(cart))}
function count(){document.querySelectorAll('#cartCount').forEach(x=>x.textContent=cart.length)}
function card(p){return `<article class="card"><div class="thumb ${p.type.toLowerCase()}"><span class="badge">${p.type}</span><small>${p.tag}</small></div><div class="cardbody"><div class="rating">★ ${p.rating}</div><h3>${p.name}</h3><p>${p.desc}</p><div class="cardfoot"><strong>${money(p.price)}</strong><button class="btn small" onclick="addToCart(${p.id})">Add to cart</button></div><a class="muted" href="product.html?id=${p.id}">View details →</a></div></article>`}
function addToCart(id){if(!cart.includes(id))cart.push(id);save();count();window.location.href='cart.html'}
function renderFeatured(){let e=document.getElementById('featuredGrid');if(e)e.innerHTML=PRODUCTS.slice(0,6).map(card).join('')}
function renderMarketplace(){let q=(document.getElementById('search')?.value||'').toLowerCase(),cat=document.getElementById('category')?.value||'all',sort=document.getElementById('sort')?.value||'featured';let a=PRODUCTS.filter(p=>(cat==='all'||p.type===cat)&&(p.name+p.desc).toLowerCase().includes(q));if(sort==='low')a.sort((x,y)=>x.price-y.price);if(sort==='high')a.sort((x,y)=>y.price-x.price);let e=document.getElementById('marketGrid');if(e)e.innerHTML=a.map(card).join('')}
function renderProduct(){let e=document.getElementById('productPage');if(!e)return;let p=PRODUCTS.find(x=>x.id==new URLSearchParams(location.search).get('id'))||PRODUCTS[0];e.innerHTML=`<a href="marketplace.html" class="muted">← Back to marketplace</a><div class="product-detail"><div class="detailvisual ${p.type.toLowerCase()}"><span class="badge">${p.type}</span><b>${p.tag}</b></div><div><p class="eyebrow">${p.type} • ★ ${p.rating}</p><h1>${p.name}</h1><p class="lead">${p.desc}</p><ul class="features"><li>Digital product delivery</li><li>Compatibility and installation information</li><li>Version/update information from the developer</li><li>Customer dashboard access after purchase</li></ul><div class="buybar"><strong>${money(p.price)}</strong><button class="btn primary" onclick="addToCart(${p.id})">Add to cart</button></div><div class="notice">Trading involves risk. No trading bot, indicator or strategy guarantees profits. Test products on demo accounts and use appropriate risk management.</div></div></div>`}
function renderCart(){let e=document.getElementById('cartItems');if(!e)return;let ps=cart.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean),total=ps.reduce((s,p)=>s+p.price,0);e.innerHTML=ps.length?ps.map(p=>`<div class="cartitem"><div><b>${p.name}</b><small>${p.type} • ${p.tag}</small></div><strong>${money(p.price)}</strong><button class="remove" onclick="removeCart(${p.id})">×</button></div>`).join(''):'<p class="muted">Your cart is empty. <a href="marketplace.html">Browse products →</a></p>';document.getElementById('subtotal')&&(document.getElementById('subtotal').textContent=money(total));document.getElementById('total')&&(document.getElementById('total').textContent=money(total))}
function removeCart(id){cart=cart.filter(x=>x!==id);save();count();renderCart()}
function renderCheckout(){let e=document.getElementById('checkoutItems');if(!e)return;let ps=cart.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean),t=ps.reduce((s,p)=>s+p.price,0);e.innerHTML=ps.map(p=>`<p>${p.name}<br><small>${money(p.price)}</small></p>`).join('')||'<p class="muted">No products.</p>';document.getElementById('checkoutTotal').textContent=money(t)}
function placeOrder(ev){ev.preventDefault();if(!cart.length){alert('Your cart is empty.');return}let email=document.getElementById('checkoutEmail').value;orders.push({id:'ORD-'+Date.now(),email,items:[...cart],total:cart.map(id=>PRODUCTS.find(p=>p.id===id)).filter(Boolean).reduce((s,p)=>s+p.price,0),date:new Date().toISOString()});localStorage.setItem('sdt_orders',JSON.stringify(orders));cart=[];save();alert('Demo order created successfully. Connect a real payment gateway before accepting live payments.');location.href='dashboard.html'}
function renderDashboard(){let e=document.getElementById('downloads');if(!e)return;document.getElementById('orderCount').textContent=orders.length;let ids=[...new Set(orders.flatMap(o=>o.items))];document.getElementById('ownedCount').textContent=ids.length;e.innerHTML=ids.length?ids.map(id=>{let p=PRODUCTS.find(x=>x.id===id);return `<div class="admin-row"><div><b>${p.name}</b><small class="muted">${p.type} • ${p.file}</small></div><button class="btn small" onclick="downloadDemo('${p.file}')">Download</button></div>`}).join(''):'<p class="muted">No purchases yet.</p>'}
function downloadDemo(file){alert('Demo download: '+file+'\n\nReplace this with secure signed file downloads on your backend.')}
function renderAdmin(){let e=document.getElementById('adminProductsList');if(!e)return;document.getElementById('adminProducts').textContent=PRODUCTS.length;document.getElementById('adminOrders').textContent=orders.length;document.getElementById('adminRevenue').textContent=money(orders.reduce((s,o)=>s+o.total,0));e.innerHTML=PRODUCTS.map(p=>`<div class="admin-row"><div><b>${p.name}</b><small class="muted">${p.type} • ${money(p.price)}</small></div><span class="muted">Published</span></div>`).join('')}
function addDemoProduct(){alert('Demo admin action. Connect a database/API to create real products and upload protected files.')}
function demoLogin(e){e.preventDefault();localStorage.setItem('sdt_user',document.getElementById('email').value);location.href='dashboard.html'}
count();renderFeatured();renderMarketplace();renderProduct();renderCart();renderCheckout();renderDashboard();renderAdmin();